
services:

  cart-service:
    build: ./cart-service
    container_name: cart-service
    ports:
      - "8081:8081"
    networks:
      - Mall
    restart: always

  hm-gateway:
    build: ./hm-gateway
    container_name: gateway
    ports:
      - "8080:8080"
    networks:
      - Mall
    restart: always

  item-service:
    build: ./item-service
    container_name: item-service
    ports:
      - "8084:8084"
    networks:
      - Mall
    restart: always

  pay-service:
    build: ./pay-service
    container_name: pay-service
    ports:
      - "8085:8085"
    networks:
      - Mall
    restart: always

  trade-service:
    build: ./trade-service
    container_name: trade-service
    ports:
      - "8086:8086"
    networks:
      - Mall
    restart: always

  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8087:8087"
    networks:
      - Mall
    restart: always

  search-service:
    build: ./search-service
    container_name: search-service
    ports:
      - "8088:8088"
    networks:
      - Mall
    restart: always

  nginx:
    image: nginx  # 使用的镜像
    container_name: nginx  # 容器名称
    ports:
      - "18080:18080"  # 映射端口
      - "18081:18081"
    volumes:
      - ./nginx/html:/usr/nginx/html  # 挂载 HTML 文件目录
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # 挂载 Nginx 配置文件
    networks:
      - Mall
    restart: always

  sentinel:
    build: ./sentinel
    container_name: sentinel
    ports:
      - "8090:8090"
    networks:
      - Mall
    restart: always

networks:
  Mall:
    name: mall

